Update tests.yaml

diff --git a/helm/templates/tests.yaml b/helm/templates/tests.yaml
--- a/helm/templates/tests.yaml
+++ b/helm/templates/tests.yaml
@@ -15,5 +15,5 @@ spec:
         - /bin/bash
         - -ec
         - |
-                    echo "Tests are successful!"
+                    echo "Tests have failed!";exit 1
   restartPolicy: Never
